on: push

jobs:
  type-check-js:
    name: "Type check: JS library"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./js

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies and type check
        run: pnpm install --frozen-lockfile

      - name: Run TSC
        run: pnpm tsc **/*.ts --noEmit --esModuleInterop
